language: node_js
node_js:
  - "lts/*"
cache: npm
before_script:
  - npm ci
script:
  - npm run build
  - npm test

deploy:
  provider: script
  script: echo $NPMRC >> ~/.npmrc && npm ci && npm run rimraf app/package-lock.json && npm run publish:canary
  on:
    branch: develop
