language: node_js
node_js:
  - "lts/*"
cache: npm
before_script:
  - npm ci
script:
  - npm run build
  - npm test

before_deploy:
  - npm ci
deploy:
  - provider: script
    script: |
              /usr/bin/expect <<EOD
              spawn npm adduser --scope@orbit-model
              expect {
                  "Username:" {send "bernhard---h\r"; exp_continue}
                  "Password:" {send "$NPM_REGISTRY_TOKEN\r"; exp_continue}
                  "Email: (this IS public)" {send "halbart.bernhard+npm@gmail.com\r"; exp_continue}
              }
              EOD && npm run pubilsh:canary
    on:
      branch: develop
#  - provider: script
#    script:
#    on:
#      branch: master
#      tags: true
