language: node_js
node_js:
  - "lts/*"
cache: npm
before_script:
  - npm ci
script:
  - npm run build
  - npm test

before_deploy:
  - node --version
  - npm version
  - npm ci
deploy:
  - provider: script
    skip_cleanup: true
    script: |
      npm adduser --scope@orbit-model <<!
        bernhard---h
        $NPM_REGISTRY_TOKEN
        halbart.bernhard+npm@gmail.com
      ! && npm run pubilsh:canary
    on:
      branch: develop
