language: node_js
node_js:
  - "lts/*"
cache: npm
before_script:
  - npm ci
script:
  - npm run build
  - npm test

#deploy:
#  provider: script
#  script: echo "@orbit-model:registry=https://registry.npmjs.org/" > ~/.npmrc && echo $NPMRC >> ~/.npmrc && npm ci && npm run publish:canary
#  on:
#    branch: develop
