language: node_js
node_js:
  - "lts/*"
cache: npm
before_script:
  - npm ci
script:
  - npm run build
  - npm test

before_deploy:
deploy:
#  - provider: npm
##    script: npm run publish:canary
#    email: halbart.bernhard+npm@gmail.com
#    api_key: $NPM_REGISTRY_TOKEN
#    on:
#      branch: develop
  - provider: script
    script: |
      node --version &&
      npm version &&
      npm ci &&
      npm adduser --scope=@orbit-model <<!
        bernhard---h
        $NPM_REGISTRY_TOKEN
        halbart.bernhard+npm@gmail.com
      ! && npm run pubilsh:canary
    on:
      branch: develop
