language: node_js
node_js:
  - "lts/*"
cache: npm
before_script:
  - yarn ci
script:
  - yarn run prettier:check
  - yarn run build
  - yarn run test
  - cd app && npm run build
  - cd dist && node ./index.js
