import Branch from "./Branch";

export default interface OrbitModelMeta {
  className: string,
  branch: Branch,
  orbitUUID: string;    // an autogenerated UUID from orbit's internals
  id: {
    remoteId?: string;
    // [key: string]: any;
  };
  values: {
    [key: string]: any;
  }
}
