import Branch from "./Branch";

export default interface OrbitModelMeta {
  className: string;
  branch: Branch;
  orbitUUID: string; // an autogenerated UUID from orbit's internals
  isDeleted: boolean; // deleted from a parent source (and the server)
  isDestroyed: boolean; // called destroy method on current branch
  ids: {
    remoteId?: string;
    // [key: string]: any;
  };
  values: {
    [key: string]: any;
  };
}
