import Branch from './Branch';

export default interface HiddenOrbit {
  klass: { new(): any };    // just to get easy access to the static reflection property
  identifier?: HiddenIDs;
  branch?: Branch
  // [key: string]: any;
}

export interface HiddenIDs {
  id: string;    // probably an autogenerated UUID from orbit's internals
  keys: {
    remoteId?: string;
    // [key: string]: any;
  };
}
