import LiteBranch from "./LiteBranch";

export default interface OrbitModelMeta<MODEL> {
  className: string,
  branch: LiteBranch<MODEL>,
  orbitUUID?: string;    // an autogenerated UUID from orbit's internals
  id: {
    remoteId?: string;
    // [key: string]: any;
  };
  values: {
    [key: string]: any;
  }
}
