import Branch from "@orbit-model/branching";

export default interface OrbitModelMeta<MODEL> {
  className: string,
  branch: Branch<MODEL>,
  orbitUUID: string;    // an autogenerated UUID from orbit's internals
  id: {
    remoteId?: string;
    // [key: string]: any;
  };
  values: {
    [key: string]: any;
  }
}
